### PR TITLE
Read offset and other header values

### PR DESCRIPTION
**Pull request by adrium**
Hey Wolfgang, found your tool when I tried to decompress an [old installer](https://winworldpc.com/product/netscape-navigator/2x).
However, some investigation was needed, because it was a multi-volume archive.

I added a lot of variables which will be useful for multi-volume archive support.

### CODE REVIEW

**Comment by dadreamer** [comment]
Hi, @adrium !

Do I understand correctly that the multi-volume support is not yet finished? I have compiled the recent unshieldv3 (incl. your revision) and tested it a little on various archives from that "Netscape Navigator Personal Edition 2.0 (3.5)" package. For example, `unshieldv3 list ./disk2/netscape.1` shows

> HANDBK.ICO
HANDBOOK\DOCS\APPANS.HTM
HANDBOOK\DOCS\ATOZ.HTM
HANDBOOK\DOCS\BEFORE.HTM
HANDBOOK\DOCS\GRAPHICS.HTM
HANDBOOK\DOCS\INTRO.HTM
HANDBOOK\DOCS\LEARN.HTM
HANDBOOK\DOCS\LEGAL.HTM
HANDBOOK\DOCS\MENUS.HTM
HANDBOOK\DOCS\MNB.HTM
HANDBOOK\DOCS\PANELS.HTM
HANDBOOK\IMAGES\NAVIGAT.GIF
HANDBOOK\IMAGES\NEWSREF.GIF
HANDBOOK\INDEX.HTM
LICENSE
NAPLAYER.EXE
NETSCAPE.EXE
NETSCAPE.HLP
NHANDBK.ICO
NSCAPE16.TLB
PLUGINS\NPNUL16.DLL
README.TXT

But when I try to extract it (`unshieldv3 extract ./disk2/netscape.1 ./extr`) I'm getting this:

> HANDBK.ICO
      Compressed size:        262
    Uncompressed size:        766
HANDBOOK\DOCS\APPANS.HTM
      Compressed size:      26647
Blast error: -1
    Uncompressed size:          0
HANDBOOK\DOCS\ATOZ.HTM
      Compressed size:       6601
Blast error: -1
    Uncompressed size:          0
HANDBOOK\DOCS\BEFORE.HTM
      Compressed size:       7397
terminate called after throwing an instance of 'std::runtime_error'
  what():  Read failed

As the result I have APPANS.HTM and ATOZ.HTM of 0 KB and HANDBK.ICO of 766 bytes. No any other files. Maybe I'm doin' smth wrong?.. Then how to extract such multi-part archives? I already tried to put all the parts (".1", ".2" etc.) into the same folder and extract, but it didn't change anything.

By the way, single-part archives (like \disk2\DIALER.Z) are processed properly.

**Comment by adrium** [comment]
Correct, multi-volume support is not finished at all.
This PR merely introduces header fields that will be useful.
The actual implementation needs to be able to load multiple files and concatenate its parts.
I am not a skilled C++ dev and have no suggestion how to extend the current architecture of the tool.

**Comment by adrium** [comment]
Out of curiosity, I wanted to extract NETSCAPE.EXE, but I have not had interest in other archives.
Based on reverse engineering, I created a file that will be readable by unshieldv3.
To help understanding and for future reference, this is how NETSCAPE.EXE can be successfully unpacked.

Source files:

```
$ md5sum NETSCAPE.*
f49c5d91f163519a4c73ae2de75dbd42  NETSCAPE.1
b455d9ded4be2733a8a7e381542b2bc2  NETSCAPE.2
ecdb36287cad22efb0378abb065852c0  NETSCAPE.3

$ xxd -g 2 -c 33 -l 66 NETSCAPE.1
00000000: 135d 658c 3a01 0200 0000 0100 1600 6c20 eaab e6b4 1600 eb70 1d00 ff00 0000 0301 d1  .]e.:.........l .......p.........
00000021: b755 0100 0000 0000 b7b5 0500 6200 0000 0500 19b6 0500 8f04 0000 0000 0000 0000 00  .U..........b....................

$ xxd -g 2 -c 33 -l 66 NETSCAPE.2
00000000: 135d 658c 3a01 0200 0000 0100 1600 6c20 eaab e6b4 1600 eb70 1d00 0000 0000 0002 d1  .]e.:.........l .......p.........
00000021: 0000 0000 ffa0 0900 ffa0 0900 6200 0000 0500 61a1 0900 8f04 0000 0000 0000 0000 00  ............b.....a..............

$ xxd -g 2 -c 33 -l 66 NETSCAPE.3
00000000: 135d 658c 3a01 0200 0000 0100 1600 6f20 0177 e6b4 1600 eb70 1d00 9ece 0400 0003 d1  .]e.:.........o .w.....p.........
00000021: 0000 0000 adc9 0400 3d5b 0700 6200 0000 0500 9f5b 0700 8f04 0000 0000 0000 0000 00  ........=[..b......[.............
```

The following bash script generates a file that can be used to extract:

```bash
toc_address=$((16#05b5b7 + 16#09a0ff + 16#075b3d - 255 - 255)) # values at offset 0x29
echo $toc_address # convert 1486837 to little-endian
printf '\xf5\xaf\x16\x00' > NETSCAPE.X

dd conv=notrunc bs=1 if=NETSCAPE.1 of=NETSCAPE.Z
dd conv=notrunc bs=1 if=NETSCAPE.2 of=NETSCAPE.Z skip=255 seek=$((16#05b5b7))
dd conv=notrunc bs=1 if=NETSCAPE.3 of=NETSCAPE.Z skip=255 seek=$((16#05b5b7 + 16#09a0ff - 255))
dd conv=notrunc bs=1 if=NETSCAPE.1 of=NETSCAPE.Z skip=$((16#05b5b7)) seek=$toc_address
dd conv=notrunc bs=1 if=NETSCAPE.X of=NETSCAPE.Z seek=$((16#29))

unshieldv3 extract NETSCAPE.Z .
md5sum NETSCAPE.EXE # a56c1e6657d4b8d49ea04f4f2c0d2607
```

**Comment by dadreamer** [comment]
Thanks for these insights and the script! I tried it now on the same archive with the same checksums. To my regret it was able to properly extract only 5 files: HANDBK.ICO, NAPLAYER.EXE, NETSCAPE.EXE, NHANDBK.ICO and NSCAPE16.TLB. For the rest unshieldv3 reported `"Blast error: -1"` and created 0 KB files instead. The official ICOMP.EXE also could not extract the entire contents. Seems like the resulting .Z file was not crafted correctly (even if it had the same checksum as in your script).

Well, I googled a bit again and found [Idecomp](https://github.com/lephilousophe/idecomp) tool, written in Python. It was able to extract all the files without any error (switch `-a` was required). I'll test it a little more on my own archives and likely stop at it. Now there's something for unshieldv3 to borrow and integrate.

**Comment by adrium** [comment]
> how NETSCAPE.EXE can be successfully unpacked

And only that...

The rest can also be unpacked when specifying the volume using `unshieldv3 extract NETSCAPE.3 .` directly.

Anyway, great that you found another tool - it seems more complete. Thanks for sharing!

**Comment by wfr** [comment]
Thank you very much for your suggestions and the pull request. You added quite a number of useful fields. Nice!

**Comment by wfr** [comment]
Merged. Thanks!

**Pull request merged**
